config/routes.rb
Rails.application.routes.draw do
  get             'calendars/index'

  get             'home',             to: 'home#index'
  get             'home/history',     to: 'home#history'

  get             '/login',           to: 'sessions#new'
  post            '/login',           to: 'sessions#create'
  delete          '/logout',          to: 'sessions#destroy'

  resources       :bookings
  resources       :users
  resources       :admins

  resources       :rooms
  get             '/search/rooms',     to: 'rooms#search'
  post            '/privilege',        to: 'users#togglePrivilege'
  root 'sessions#new'
end

app/views/admins/_form.html.erb
<%= form_for(@user, :url => admins_path, :html => {:class => "form-horizontal"}) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation" class="alert alert-dismissable alert-danger">
          <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :email, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :name, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.password_field :password, class: "form-control", placeholder: "Password (type in new password or leave blank for no change)", autocomplete: "off" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :address, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_area :address, class: "form-control", placeholder: "Address" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :phone, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_area :phone, class: "form-control", placeholder: "Phone Number" %>
      </div>
    </div>

    <br>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/admins/edit.html.erb
<% if logged_in? and @user %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Edit User</h1>
          </div>
          <%= render 'form', user: @user %>
        </div>
      </div>
    </div>

    <%= link_to 'Cancel', users_path, class: "btn btn-primary" %>
<% end %>

app/views/admins/index.html.erb
<% if logged_in? and @users %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Manage Admins</h1>
          </div>

          <div class="col-lg-10 col-lg-offset-1">
            <table class="table table-striped table-hover ">
              <thead>
              <tr>
                <th>Email</th>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
                <th colspan="3"></th>
              </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                  <% if user.admin %>
                      <tr>
                        <td><%= user.email %></td>
                        <td><%= user.name %></td>
                        <td><%= user.address %></td>
                        <td><%= user.phone %></td>
                        <td><%= link_to 'Show', admin_path(user), class: "text-info" %></td>
                        <% if user.removable and current_user.email != user.email %>
                            <td><%= link_to 'Destroy', admin_path(user), method: :delete, data: {confirm: 'Are you sure?'}, class: "text-danger" %></td>
                        <% end %>
                      </tr>
                  <% end %>
              <% end %>
              </tbody>
            </table>
            <%= link_to 'New Admin', new_admin_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= link_to 'Back to Home', home_path, class: "btn btn-primary" %>
<% end %>

app/views/admins/new.html.erb
<% if logged_in? and @user %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Register New Admin</h1>
          </div>
          <%= render 'form', user: @user %>
        </div>
      </div>
    </div>

    <%= link_to 'Cancel', admins_path, class: "btn btn-primary" %>

<% end %>

app/views/admins/show.html.erb
<% if logged_in? and @user %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Admin Details</h1>
          </div>

          <div class="col-lg-10 col-lg-offset-1">
            <table class="table table-striped table-hover table-bordered">
              <tbody>
              <tr>
                <td class="col-lg-5">Email</td>
                <td class="active"><%= @user.email %></td>
              </tr>
              <tr>
                <td>Name</td>
                <td class="active"><%= @user.name %></td>
              </tr>
              <tr>
                <td>Address</td>
                <td class="active"><%= @user.address %></td>
              </tr>
              <tr>
                <td>Phone</td>
                <td class="active"><%= @user.phone %></td>
              </tr>
              <tr>
                <td>Admin?</td>
                <td class="active"><%= @user.admin %></td>
              </tr>
              </tbody>
            </table>
            <% if current_user.email == @user.email %>
                <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= link_to 'Back to Admins', admins_path, class: "btn btn-primary" %>
<% end %>