config/routes.rb
Rails.application.routes.draw do
  get             'calendars/index'

  get             'home',             to: 'home#index'
  get             'home/history',     to: 'home#history'

  get             '/login',           to: 'sessions#new'
  post            '/login',           to: 'sessions#create'
  delete          '/logout',          to: 'sessions#destroy'

  resources       :bookings
  resources       :users
  resources       :admins

  resources       :rooms
  get             '/search/rooms',     to: 'rooms#search'
  post            '/privilege',        to: 'users#togglePrivilege'
  root 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :phone, numericality: {only_integer: true}
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def togglePrivilege
    @user = User.find_by(email: params[:email])
    @user.privilege = !@user.privilege
    if @user.save
      redirect_to users_path, notice: "User privilege updated"
    else
      redirect_to users_path
    end
  end

  # GET /users
  # GET /users.json
  def index
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    elsif !current_user.admin
      flash.now[:danger] = "You are not authorized to view this page."
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    else
      @user = User.find(params[:id])
      if !current_user.admin and current_user.email != @user.email
        flash.now[:danger] = "You are not authorized to view this user's details."
        @user = nil
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    else
      @user = User.find(params[:id])
      if current_user.email != @user.email
        flash.now[:danger] = "You cannot edit another user's profile."
        @user = nil
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.admin = false
    @user.removable = true
    @user.privilege = false
    if @user.save
      if !logged_in?
        log_in @user
      end
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    flag = false
    if @user.email == current_user.email
      flag = true
    end
    if @user.update(user_params)
      @user.admin = false
      @user.removable = true
      if flag
        log_out
        log_in(@user)
      end
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.removable
      if @user.email == current_user.email
        log_out
        @user.destroy
        redirect_to root_url, notice: 'User was successfully destroyed.'
      else
        @user.destroy
        redirect_to users_url, notice: 'User was successfully destroyed.'
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :name, :password, :address, :phone, :admins, :removable, :privilege)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def hideadmin
    showadmin = false
  end
  def showadmin
    showadmin = true
  end
end

app/views/users/_form.html.erb
<%= form_for(user, :html => {:class => "form-horizontal"}) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation" class="alert alert-dismissable alert-danger">
          <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :email, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :name, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.password_field :password, class: "form-control", placeholder: "Password", autocomplete: "off" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :address, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_area :address, class: "form-control", placeholder: "Address" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :phone, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.text_area :phone, class: "form-control", placeholder: "Phone Number" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :admin, class: "col-lg-2 control-label" %>
      <div class="col-lg-1">
        <%= f.check_box :admin, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :privilege, class: "col-lg-2 control-label" %>
      <div class="col-lg-1">
        <%= f.check_box :privilege, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :removable, class: "col-lg-2 control-label" %>
      <div class="col-lg-1">
        <%= f.check_box :removable, class: "form-control", checked: true, disabled: true %>
      </div>
    </div>

    <br>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<% if logged_in? and @user %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Edit User</h1>
          </div>
          <%= render 'form', user: @user %>
        </div>
      </div>
    </div>

    <% if logged_in? %>
        <% if current_user.admin %>
            <%= link_to 'Cancel', users_path, class: "btn btn-primary" %>
        <% else %>
            <%= link_to 'Cancel', @user, class: "btn btn-primary" %>
        <% end %>
    <% else %>
        <%= link_to 'Cancel', root_path, class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<% if logged_in? and @users %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Manage Users</h1>
          </div>

          <div class="col-lg-10 col-lg-offset-1">
            <table class="table table-striped table-hover ">
              <thead>
              <tr>
                <th>Email</th>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Multi-booking Privilege</th>
                <th colspan="3"></th>
              </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                  <% if !user.admin %>
                      <tr>
                        <td><%= user.email %></td>
                        <td><%= user.name %></td>
                        <td><%= user.address %></td>
                        <td><%= user.phone %></td>
                        <% if user.privilege %>
                            <td class="success"><%= link_to 'Yes', privilege_path(:email => user.email), method: 'post' %></td>
                        <% else %>
                            <td class="danger"><%= link_to 'No', privilege_path(:email => user.email), method: 'post' %></td>
                        <% end %>
                        <td><%= link_to 'Show', user, class: "text-info" %></td>
                        <td><%= link_to 'Reservation History', user, class: "text-warning" %></td>
                        <% if user.removable %>
                            <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'}, class: "text-danger" %></td>
                        <% end %>
                      </tr>
                  <% end %>
              <% end %>
              </tbody>
            </table>
            <%= link_to 'New User', new_user_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= link_to 'Back to Home', home_path, class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1>Register New User</h1>
      </div>
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

<% if logged_in? %>
    <% if current_user.admin %>
        <%= link_to 'Cancel', users_path, class: "btn btn-primary" %>
    <% else %>
        <%= link_to 'Cancel', home_path, class: "btn btn-primary" %>
    <% end %>
<% else %>
    <%= link_to 'Cancel', root_path, class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<% if logged_in? and @user %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>User Details</h1>
          </div>

          <div class="col-lg-10 col-lg-offset-1">
            <table class="table table-striped table-hover table-bordered">
              <tbody>
              <tr>
                <td class="col-lg-5">Email</td>
                <td class="active"><%= @user.email %></td>
              </tr>
              <tr>
                <td>Name</td>
                <td class="active"><%= @user.name %></td>
              </tr>
              <tr>
                <td>Address</td>
                <td class="active"><%= @user.address %></td>
              </tr>
              <tr>
                <td>Phone</td>
                <td class="active"><%= @user.phone %></td>
              </tr>
              <tr>
                <td>Admin?</td>
                <% if @user.admin %>
                    <td class="active">Yes</td>
                <% else %>
                    <td class="active">No</td>
                <% end %>
              </tr>
              <tr>
                <td>Has privilege to do multiple bookings?</td>
                <% if @user.privilege %>
                    <td class="success">Yes</td>
                <% else %>
                    <td class="danger">No</td>
                <% end %>
              </tr>
              </tbody>
            </table>
            <% if current_user.email == @user.email %>
                <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <% if logged_in? and current_user.admin %>
        <%= link_to 'Back to Users', users_path, class: "btn btn-primary" %>
    <% end %>
<% end %>