config/routes.rb
Rails.application.routes.draw do
  get             'calendars/index'

  get             'home',             to: 'home#index'
  get             'home/history',     to: 'home#history'

  get             '/login',           to: 'sessions#new'
  post            '/login',           to: 'sessions#create'
  delete          '/logout',          to: 'sessions#destroy'

  resources       :bookings
  resources       :users
  resources       :admins

  resources       :rooms
  get             '/search/rooms',     to: 'rooms#search'
  post            '/privilege',        to: 'users#togglePrivilege'
  root 'sessions#new'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    end
  end

  def history
    @booking = Booking.new
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    elsif !current_user.admin
      flash.now[:danger] = 'You are not authorized to view this page.'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/history.html.erb
<% if logged_in? %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Search Booking History By</h1>
          </div>

          <div class="container">

            <h6>You can search booking history by user, room, or both.</h6>
            <% if current_user.admin %>
                <%= form_for(@booking, :url => bookings_path, :method => 'get', :html => {:class => "form-horizontal"}) do |f| %>
                    <% if @booking.errors.any? %>
                        <div id="error_explanation" class="alert alert-dismissable alert-danger">
                          <%= pluralize(@booking.errors.count, "error") %> prohibited this user from being saved:

                          <ul>
                            <% @booking.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                          </ul>
                        </div>
                    <% end %>

                    <div class="form-group">
                      <%= f.label :email, class: "col-lg-2 control-label" %>
                      <div class="col-lg-5">
                        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
                      </div>
                    </div>

                    <div class="form-group">
                      <%= f.label :room, class: "col-lg-2 control-label" %>
                      <div class="col-lg-5">
                        <%= f.number_field :room, class: "form-control", placeholder: "Room" %>
                      </div>
                    </div>

                    <br>
                    <div class="form-group">
                      <div class="col-lg-10 col-lg-offset-2">
                        <%= f.submit "Submit", class: "btn btn-default" %>
                      </div>
                    </div>
                <% end %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Back to Home', home_path, class: "btn btn-primary" %>
<% end %>

app/views/home/index.html.erb
<% if logged_in? %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Home</h1>
          </div>

          <div class="container">

            <% if current_user.admin %>
                <%= link_to "Manage Users", users_path, class: "navbar-brand" %>
                <%= link_to "Manage Admins", admins_path, class: "navbar-brand" %>
                <%= link_to "Manage Rooms", rooms_path, class: "navbar-brand" %>
                <%= link_to "Booking History", home_history_path, class: "navbar-brand" %>
                <%= link_to "Booking Calendar", calendars_index_path, class: "navbar-brand" %>
            <% else %>
                <%= link_to "Search Rooms", search_rooms_path, class: "navbar-brand" %>
                <%= link_to "Booking History", bookings_path, class: "navbar-brand" %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
<% end %>