config/routes.rb
Rails.application.routes.draw do
  get             'calendars/index'

  get             'home',             to: 'home#index'
  get             'home/history',     to: 'home#history'

  get             '/login',           to: 'sessions#new'
  post            '/login',           to: 'sessions#create'
  delete          '/logout',          to: 'sessions#destroy'

  resources       :bookings
  resources       :users
  resources       :admins

  resources       :rooms
  get             '/search/rooms',     to: 'rooms#search'
  post            '/privilege',        to: 'users#togglePrivilege'
  root 'sessions#new'
end

app/models/room.rb
class Room < ApplicationRecord
  attr_accessor :sizetext, :status
  validates :building, :size, presence: true
  validates :number, presence: true, numericality: {only_integer: true}, uniqueness: true

  def self.search (params)
    if params[:number].present?
      if params[:building].present?
        if params[:size].present?
          where("number = ? and building LIKE ? and size = ?", params[:number], params[:building], params[:size])
        else
          where("number = ? and building LIKE ?", params[:number], params[:building])
        end
      else
        if params[:size].present?
          where("number = ? and size = ?", params[:number], params[:size])
        else
          where("number = ?", params[:number])
        end
      end
    else
      if params[:building].present?
        if params[:size].present?
          where("building LIKE ? and size = ?", params[:building], params[:size])
        else
          where("building LIKE ?", params[:building])
        end
      else
        where("size = ?", params[:size])
      end
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def schedule
    # Show schedule of all rooms
  end

  def history
    # Show booking history of room
  end

  def search
    if params[:room].blank?
      @room = Room.new
    else
      @room = Room.new(room_params)
    end
    if params[:room] and (params[:room][:number] or params[:room][:building] or params[:room][:size])
      @rooms = Room.search(params[:room])
      if !@rooms.present?
        @rooms = nil
      else
        @rooms.each do |room|
          set_size_text room
        end
      end
    end
  end

  # GET /rooms
  # GET /rooms.json
  def index
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    elsif !current_user.admin
      flash.now[:danger] = 'You are not authorized to view this page.'
    else
      @rooms = Room.all
      @rooms.each do |room|
        set_size_text room
      end
    end
    # Add booked field based on start and end date
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    else
      @room = Room.find(params[:id])
      @room.status = 'Available'
      set_size_text @room
      email = Booking.searchUserBookedRoom(@room.number)
      @user = User.find_by(email: email)
      if @user.present?
        @room.status = 'Booked'
      end
      if !current_user.admin
        @user = nil
      end
      # Show booking history button
    end
  end

  # GET /rooms/new
  def new
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    elsif !current_user.admin
      flash.now[:danger] = 'You are not authorized to view this page.'
    else
      @room = Room.new
    end
  end

  # GET /rooms/1/edit
  def edit
    if !logged_in?
      flash.now[:danger] = 'You are not logged in. Please login to continue.'
    else
      @room = Room.find(params[:id])
      set_size_text @room
      if !current_user.admin
        flash.now[:danger] = "You are not authorized to view this page."
        @room = nil
      else
        # Admin can change status of room (book/release for member)
      end
    end
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end

  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end

  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private

  def set_size_text (room)
    if room
      if room.size == 4
        room.sizetext = 'Small (4)'
      elsif room.size == 6
        room.sizetext = 'Medium (6)'
      else
        room.sizetext = 'Large (12)'
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find_by_id(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:number, :building, :size)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room, :html => {:class => "form-horizontal"}) do |f| %>
    <% if room.errors.any? %>
        <div id="error_explanation" class="alert alert-dismissable alert-danger">
          <%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:

          <ul>
            <% room.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label 'Room Number', class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.number_field :number, class: "form-control", placeholder: "Room Number" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :building, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.select :building, [['D. H. Hill', 'D. H. Hill'], ['James B. Hunt', 'James B. Hunt']],
                     {}, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :size, class: "col-lg-2 control-label" %>
      <div class="col-lg-5">
        <%= f.select :size, [['Small (4)', 4], ['Medium (6)', 6], ['Large (12)', 12]],
                     {}, class: "form-control" %>
      </div>
    </div>

    <br>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
    </div>
<% end %>

app/views/rooms/edit.html.erb
<% if logged_in? and @room %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Edit Room</h1>
          </div>
          <%= render 'form', room: @room %>
        </div>
      </div>
    </div>

    <%= link_to 'Cancel', rooms_path, class: "btn btn-primary" %>
<% end %>

app/views/rooms/index.html.erb
<% if logged_in? and @rooms %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Manage Rooms</h1>
          </div>

          <div class="col-lg-10 col-lg-offset-1">
            <table class="table table-striped table-hover ">
              <thead>
              <tr>
                <th>Number</th>
                <th>Building</th>
                <th>Size</th>
                <th colspan="3"></th>
              </tr>
              </thead>
              <tbody>
              <% @rooms.each do |room| %>
                  <tr>
                    <td><%= room.number %></td>
                    <td><%= room.building %></td>
                    <td><%= room.sizetext %></td>
                    <td><%= link_to 'Show', room, class: "text-info" %></td>
                    <td><%= link_to 'Edit', edit_room_path(room), class: "text-warning" %></td>
                    <td><%= link_to 'Destroy', room, method: :delete, data: {confirm: 'Are you sure?'}, class: "text-danger" %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <%= link_to 'New Room', new_room_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= link_to 'Back to Home', home_path, class: "btn btn-primary" %>
<% end %>

app/views/rooms/new.html.erb
<% if logged_in? and @room %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Register New Room</h1>
          </div>
          <%= render 'form', room: @room %>
        </div>
      </div>
    </div>

    <%= link_to 'Cancel', rooms_path, class: "btn btn-primary" %>

<% end %>

app/views/rooms/search.html.erb
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1>Search Room</h1>
      </div>

      <%= form_for(@room, :url => search_rooms_path, :method => 'get', :html => {:class => "form-horizontal"}) do |f| %>

          <div class="form-group">
            <%= f.label 'Room Number', class: "col-lg-2 control-label" %>
            <div class="col-lg-5">
              <%= f.number_field :number, class: "form-control", placeholder: "Room Number" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :building, class: "col-lg-2 control-label" %>
            <div class="col-lg-5">
              <%= f.select :building, [[nil, nil], ['D. H. Hill', 'D. H. Hill'], ['James B. Hunt', 'James B. Hunt']],
                           {}, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :size, class: "col-lg-2 control-label" %>
            <div class="col-lg-5">
              <%= f.select :size, [[nil, nil], ['Small (4)', 4], ['Medium (6)', 6], ['Large (12)', 12]],
                           {}, class: "form-control" %>
            </div>
          </div>

          <br>
          <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
              <%= f.submit "Search", :name => nil, class: "btn btn-default" %>
            </div>
          </div>
      <% end %>

      <% if @rooms %>
          <div class="col-lg-10 col-lg-offset-1">
            <table class="table table-striped table-hover ">
              <thead>
              <tr>
                <th>Number</th>
                <th>Building</th>
                <th>Size</th>
                <th colspan="3"></th>
              </tr>
              </thead>
              <tbody>
              <% @rooms.each do |room| %>
                  <tr>
                    <td><%= room.number %></td>
                    <td><%= room.building %></td>
                    <td><%= room.sizetext %></td>
                    <td><%= link_to 'Show', room, class: "text-info" %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<% if logged_in? and @room %>
    <div class="bs-docs-section clearfix">
      <div class="row">
        <div class="col-lg-12">
          <div class="page-header">
            <h1>Room Details</h1>
          </div>

          <div class="col-lg-10 col-lg-offset-1">
            <table class="table table-striped table-hover table-bordered">
              <tbody>
              <tr>
                <td class="col-lg-5">Number</td>
                <td class="active"><%= @room.number %></td>
              </tr>
              <tr>
                <td>Building</td>
                <td class="active"><%= @room.building %></td>
              </tr>
              <tr>
                <td>Size</td>
                <td class="active"><%= @room.sizetext %></td>
              </tr>
              <tr>
                <td>Current Availability</td>
                <% if @room.status == 'Booked' %>
                    <td class="active danger"><%= @room.status %></td>
                <% else %>
                    <td class="active success"><%= @room.status %></td>
                <% end %>
              </tr>
              <% if @user %>
                  <tr>
                    <td>User who has the room</td>
                    <td class="active"><%= @user.email %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <% if current_user.admin %>
                <%= link_to 'Edit', edit_room_path(@room), class: "btn btn-default" %>
            <% end %>
            <%= link_to 'Book', new_booking_path(:room => @room.number), class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <% if current_user.admin %>
        <%= link_to 'Back to Rooms', rooms_path, class: "btn btn-primary" %>
    <% else %>
        <%= link_to 'Back to Search', search_rooms_path, class: "btn btn-primary" %>
    <% end %>
<% end %>